<table>
       <tr>
         <td align="right">{salutation}</td>
         <td>Salutation of recipients in mail merge</td>
       </tr>
	   <tr>
         <td align="right">{firstname}</td>
         <td>First name of recipients in mail merge</td>
       </tr>
       <tr>
         <td align="right">{surname}</td>
         <td>Surname of recipients in mail merge</td>
       </tr>
       <tr>
         <td align="right">{signature}</td>
         <td>Signature chosen in mail merge</td>
       </tr>
       <tr>
         <td align="right">{date}</td>
         <td>Supplied or today's date</td>
       </tr>
       <tr>
         <td align="right">{amount}</td>
         <td>Supplied amount - e.g. payment</td>
       </tr>
       <tr>
         <td align="right">{ref}</td>
         <td>Supplied reference</td>
       </tr>
	   <tr>
         <td align="right">{custom1}{custom2}...</td>
         <td>Custom fields</td>
       </tr>
     </table>